# Generated by Django 5.1.7 on 2025-03-17 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characterisitcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=250)),
                ('ALT', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100)),
                ('tour_description', models.TextField(max_length=800)),
                ('duration', models.IntegerField()),
                ('min_people', models.IntegerField()),
                ('photos', models.ManyToManyField(to='myApp.media')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=600)),
                ('calification', models.IntegerField(default=5)),
                ('characterisitcs', models.ManyToManyField(to='myApp.characterisitcs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.profile')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.tour')),
            ],
        ),
    ]
