# Generated by Django 5.1.7 on 2025-03-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.ManyToManyField(blank=True, null=True, to='myApp.includes'),
        ),
    ]
