# Generated by Django 5.1.7 on 2025-03-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_tour_includes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='detailed_description',
            field=models.TextField(default=' ', max_length=9800),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinereray',
            field=models.TextField(default=' ', max_length=4500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='includes',
            field=models.ManyToManyField(null=True, to='myApp.includes'),
        ),
        migrations.AddField(
            model_name='tour',
            name='recommendations',
            field=models.ManyToManyField(to='myApp.recommendations'),
        ),
    ]
