# Generated by Django 5.1.7 on 2025-03-21 03:20

import myApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_comments_user_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=myApp.models.user_directory_path),
        ),
    ]
