# Generated by Django 5.1.6 on 2025-03-15 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commentcharacteristics_includes_comment_calification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='characteristics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.commentcharacteristics'),
        ),
    ]
