# Generated by Django 5.1.6 on 2025-03-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='comment',
            name='characteristics',
            field=models.ManyToManyField(blank=True, to='app.commentcharacteristics'),
        ),
    ]
